groups:
- superherocities
- anarchy
- anarchy_nether
- boatrace
- checkers
- chess
- colosseum
- colosseumlobby
- crossfire
- deathdrop
- deathmachine
- deathrun
- elytraeasy
- elytrahard
- elytralobby
- elytramedium
- elytrapole
- elytrapvp
- escaperoom
- extremesumo
- fightclub
- flappybirdparkour
- flyingbattlearena
- flyingbattlelobby
- formuladrift
- garbageworld
- godlyparkour
- greenfield
- greenfield_the_end
- heroicparkour
- hilariousrace
- hurdles
- hurdles2
- infiniteparkour
- initiation
- kingoftheladder
- lasertag
- lavahop
- longparkour
- marathon
- mazerunner
- megaparkour
- minecraftparkourmode
- newminigamehub
- obstaclecourse
- overvoid
- parkoureasy
- parkourhard
- parkourhub
- parkourmedium
- parksideprisonescape
- plots
- pvpparkour
- pvpparkourlobby
- pvpworldsforest
- pvpworldslobby
- pvpworldsruins
- pvpworldsundergroundarmory
- quickparkour
- rollercoaster
- rules
- runner
- shortparkour
- skeeter
- skeeter_nether
- skeeter_the_end
- skywars
- skywarslobby
- soccer
- spawn
- speedforce
- spleef
- spleeflobby
- splegg
- sprintparkour
- straightlineparkour
- survival112
- survival112_nether
- survival122_the_end
- techcombatknockbackgame
- torture
- towerparkour
- turbotowers
- turfwars
- vampirez
- verticalparkour
- wallenpole
- moblottery
- infectiontag
- freezetag
- shootingrange
- kartlobby
- kartraces
worlds:
  kartlobby: kartlobby
  kartraces: kartraces
  lexstarklabs: default
  shootingrange: shootingrange
  freezetag: freezetag
  infectiontag: infetiontag
  moblottery: moblottery
  anarchy: anarchy
  anarchy_nether: anarchy
  anarchy_nether: anarchy
  boatrace: boatrace
  checkers: checkers
  chess: chess
  colosseum: colosseum
  colosseumlobby: colosseumlobby
  crossfire: crossfire
  deathdrop: deathdrop
  deathmachine: deathmachine
  deathrun: deathrun
  elytraeasy: elytraeasy
  elytrahard: elytrahard
  elytralobby: elytralobby
  elytramedium: elytramedium
  elytrapole: elytrapole
  elytrapvp: elytrapvp
  escaperoom: escaperoom
  extremesumo: extremesumo
  fightclub: fightclub
  flappybirdparkour: flappybirdparkour
  flyingbattlearena: flyingbattlearena
  flyingbattlelobby: flyingbattlelobby
  formuladrift: formuladrift
  fortressofsolitude: superherocities
  garbageworld: garbageworld
  godlyparkour: godlyparkour
  gotham: superherocities
  atlantis: superherocities
  greenfield: superherocities
  greenfield_the_end: greenfield_the_end
  hallofjustice: superherocities
  heroicparkour: heroicparkour
  hilariousrace: hilariousrace
  hurdles: hurdles
  hurdles2: hurdles2
  infiniteparkour: infiniteparkour
  infinitycity: superherocities
  initiation: initiation
  kingoftheladder: kingoftheladder
  lasertag: lasertag
  lavahop: lavahop
  longparkour: longparkour
  marathon: marathon
  mazerunner: mazerunner
  megaparkour: megaparkour
  metropolis: superherocities
  minecraftparkourmode: minecraftparkourmode
  newminigamehub: newminigamehub
  obstaclecourse: obstaclecourse
  overvoid: overvoid
  parkoureasy: parkoureasy
  parkourhard: parkourhard
  parkourhub: parkourhub
  parkourmedium: parkourmedium
  parksideprisonescape: parksideprisonescape
  plots: plots
  pvpparkour: pvpparkour
  pvpparkourlobby: pvpparkourlobby
  pvpworldsforest: pvpworldsforest
  pvpworldslobby: pvpworldslobby
  pvpworldsruins: pvpworldsruins
  pvpworldsundergroundarmory: pvpworldsundergroundarmory
  quickparkour: quickparkour
  rollercoaster: rollercoaster
  rules: rules
  runner: runner
  shortparkour: shortparkour
  skeeter: skeeter
  skeeter_nether: skeeter
  skeeter_the_end: skeeter
  skywars: skywars
  skywarslobby: skywarslobby
  soccer: soccer
  spawn: spawn
  speedforce: speedforce
  spleef: spleef
  spleeflobby: spleeflobby
  splegg: splegg
  sprintparkour: sprintparkour
  straightlineparkour: straightlineparkour
  survival112: default
  survival112_nether: default
  survival112_the_end: default
  techcombatknockbackgame: techcombatknockbackgame
  titanstower: superherocities
  torture: torture
  towerparkour: towerparkour
  turbotowers: turbotowers
  turfwars: turfwars
  underworld: underworld
  utopia: office
  vampirez: vampirez
  verticalparkour: verticalparkour
  wallenpole: wallenpole
  waynemanor: superherocities
respect-gamemode: false
