groups:
- alpha
- anarchy
- anarchy_nether
- boatrace
- checkers
- chess
- colosseum
- colosseumlobby
- crossfire
- deathdrop
- deathmachine
- deathrun
- destructiblecity
- elytraeasy
- elytrahard
- elytralobby
- elytramedium
- elytrapole
- elytrapvp
- escaperoom
- extremesumo
- fightclub
- flappybirdparkour
- flyingbattlearena
- flyingbattlelobby
- formuladrift
- fortressofsolitude
- garbageworld
- godlyparkour
- gotham
- greenfield
- greenfield_the_end
- hallofjustice
- heroicparkour
- hilariousrace
- hurdles
- hurdles2
- infiniteparkour
- infinitycity
- initiation
- kingoftheladder
- lasertag
- lavahop
- longparkour
- marathon
- mazerunner
- megaparkour
- metropolis
- minecraftparkourmode
- newcity
- newminigamehub
- obstaclecourse
- office
- overvoid
- parkoureasy
- parkourhard
- parkourhub
- parkourmedium
- parksideprisonescape
- plots
- pvpparkour
- pvpparkourlobby
- pvpworldsforest
- pvpworldslobby
- pvpworldsruins
- pvpworldsundergroundarmory
- quickparkour
- rollercoaster
- rules
- runner
- shortparkour
- skeeter
- skeeter_nether
- skeeter_the_end
- skywars
- skywarslobby
- soccer
- spawn
- speedforce
- spleef
- spleeflobby
- splegg
- sprintparkour
- straightlineparkour
- superherocity
- survival
- survival_nether
- survival_the_end
- techcombatknockbackgame
- temple
- titanstower
- torture
- towerparkour
- turbotowers
- turfwars
- underworld
- utopia
- vampirez
- verticalparkour
- wallenpole
- waterprison
- waynemanor
- wooftywoo
worlds:
  alpha: alpha
  anarchy: anarchy
  anarchy_nether: anarchy
  anarchy_nether: anarchy
  boatrace: boatrace
  checkers: checkers
  chess: chess
  colosseum: colosseum
  colosseumlobby: colosseumlobby
  crossfire: crossfire
  deathdrop: deathdrop
  deathmachine: deathmachine
  deathrun: deathrun
  destructiblecity: default
  elytraeasy: elytraeasy
  elytrahard: elytrahard
  elytralobby: elytralobby
  elytramedium: elytramedium
  elytrapole: elytrapole
  elytrapvp: elytrapvp
  escaperoom: escaperoom
  extremesumo: extremesumo
  fightclub: fightclub
  flappybirdparkour: flappybirdparkour
  flyingbattlearena: flyingbattlearena
  flyingbattlelobby: flyingbattlelobby
  formuladrift: formuladrift
  fortressofsolitude: default
  garbageworld: garbageworld
  godlyparkour: godlyparkour
  gotham: default
  greenfield: default
  greenfield_the_end: greenfield_the_end
  hallofjustice: hallofjustice
  heroicparkour: heroicparkour
  hilariousrace: hilariousrace
  hurdles: hurdles
  hurdles2: hurdles2
  infiniteparkour: infiniteparkour
  infinitycity: default
  initiation: initiation
  kingoftheladder: kingoftheladder
  lasertag: lasertag
  lavahop: lavahop
  longparkour: longparkour
  marathon: marathon
  mazerunner: mazerunner
  megaparkour: megaparkour
  metropolis: default
  minecraftparkourmode: minecraftparkourmode
  newcity: newcity
  newminigamehub: newminigamehub
  obstaclecourse: obstaclecourse
  office: office
  overvoid: overvoid
  parkoureasy: parkoureasy
  parkourhard: parkourhard
  parkourhub: parkourhub
  parkourmedium: parkourmedium
  parksideprisonescape: parksideprisonescape
  plots: plots
  pvpparkour: pvpparkour
  pvpparkourlobby: pvpparkourlobby
  pvpworldsforest: pvpworldsforest
  pvpworldslobby: pvpworldslobby
  pvpworldsruins: pvpworldsruins
  pvpworldsundergroundarmory: pvpworldsundergroundarmory
  quickparkour: quickparkour
  rollercoaster: rollercoaster
  rules: rules
  runner: runner
  shortparkour: shortparkour
  skeeter: skeeter
  skeeter_nether: skeeter
  skeeter_the_end: skeeter
  skywars: skywars
  skywarslobby: skywarslobby
  soccer: soccer
  spawn: spawn
  speedforce: speedforce
  spleef: spleef
  spleeflobby: spleeflobby
  splegg: splegg
  sprintparkour: sprintparkour
  straightlineparkour: straightlineparkour
  superherocity: default
  survival: default
  survival_nether: default
  survival_the_end: default
  techcombatknockbackgame: techcombatknockbackgame
  temple: temple
  titanstower: default
  torture: torture
  towerparkour: towerparkour
  turbotowers: turbotowers
  turfwars: turfwars
  underworld: underworld
  utopia: office
  vampirez: vampirez
  verticalparkour: verticalparkour
  wallenpole: wallenpole
  waterprison: waterprison
  waynemanor: default
  wooftywoo: wooftywoo
respect-gamemode: false
