Broadcast-Inverval: 5m
Auto-Broadcast: true
Random-Order: false
Ignore-Delay: 1h
Prefixes:
  Console: '&5[CONSOLE]&f '
  Default: ''
  '@W': '&4[WARNING]&f '
  '@T': '&5[TIP]&f '
Messages:
    - "&9TeamSpeak Server: &6mynecraft.servegame.com"
    - "&7You can be anyone you want on this server. A &9god&7, a &9superhero&7, a &9human&7, doesn't matter."
    - "&7Commands you should know: &9/recipe&7, &9/co i&7, &9/bal&7, &9/sell&7, and more! Visit &9/warp commandshall&7 !"
    - "&7Need to contact the owner? Send an email to &4malonnnnn@gmail.com"
    - "&7We now accept donations: &6https://goo.gl/BmxAqv"
    - "&7Want to join our &9staff &7team? &9Mod &7positions are available by heading to &4/warp moddapps&7!"
    - "&7Every time you &6/vote &7for us, you are rewarded &9money&7 which can be used to transform in &c&lOP &7heroes and buy/rent houses in the city!"
    - "&7Since this is an &4RP Server&7, the only classes that are allowed to &charm mortals &7are those that make sense to do so, such as &4villians&7."
    - "&7&lAttention!&7You can now go to &f/warp rules &7to see the new server rules!"