Broadcast-Inverval: 5m
Auto-Broadcast: true
Random-Order: false
Ignore-Delay: 1h
Prefixes:
  Console: '&5[CONSOLE]&f '
  Default: ''
  '@W': '&4[WARNING]&f '
  '@T': '&5[TIP]&f '
Messages:
    #  - "&b ----------------------------------------------------\n
    #&4&l&kK&a&l The &c&lWarsow Tournament&a&l &f&lis now in progress!!\n
    #&f You could win a &a10,000 prize!\n
    #&f Download Warsow ( warsow.net/download )\n
    #&f Start game, click &cNEW GAME&f, click &cINSTAGIB&f, join &cTeks Server\n
    #&4&l&kK&6&l EVERYONE WINS MONEY, EVEN IN LAST PLACE!\n
    #&b----------------------------------------------------"
    #  - "&b ----------------------------------------------------\n
    #&4&l&kK&a&l Vote on the new labs! (&c&lpls re-vote&a&l, &4&l&ofinal &b&l&onew poll&a&l)\n
    #&4&l&kK&d&l /warp lab1 lab2 lab3 lab4 lab5 lab6 lab7 lab8 lab9\n
    #&4&l&kK&e&l The Best Lab Will Become The Official Lab!\n
    #&4&l&kK&6&l http://www.strawpoll.me/13537825\n
    #&b----------------------------------------------------"
  - "&b ----------------------------------------------------\n
&7This server supports &aall canon &7(&4&lnot &4fanfic&7) &7characters&7\n
It is &lFEATS ONLY&7, meaning NO WIKIS OR FANSITES.\n
Only stuff that's &lACTUALLY&7 been shown in a comic, game,\n
TV, Movie, or other authorized merch.\n
Interpretation can still be up for debate.\n
&lONLY PICS OR VIDS COUNT AS PROOF!\n
&b----------------------------------------------------"
  - "&b ----------------------------------------------------\n
&7Handy Stuff:\n
&a/recipe&7\n
&a/co i&7\n
&a/home &f<&aplayername&f>&a: &f<-- dont forget the &a:&7\n
&a/powers&7\n
&a/mortal&7\n
&a/disguiseviewself &f(&a/dvs&f)&7\n
&a/who&7\n
&a/heroes &f<&apagenum&f>&7\n
&a/id &f<&aclassname&f>&7\n
&e&lhttps://discord.gg/QK2ebTp &7(new Discord)\n
&b----------------------------------------------------"
  - "&b ----------------------------------------------------\n
&7We now beg for irl money: &ahttps://goo.gl/BmxAqv&7\n
&b----------------------------------------------------"
#   - "&b ----------------------------------------------------\n
# &fAttention server! There is a new staff position called \n
# &c\"Helper\" &fand to be helper you must answer a quiz. The questions to the quiz have not been written, that's where YOU come in! \n
# &aPlease make a list of potential quiz questions&f, and for each well thought-out question, &4you will recieve &a$&n100&f. You can use &3hastebin.com&f to make a quick, easy list that you can save and share. Make the list, press the save icon, and share the link/URL with jiren. This offer is temporary and may expire at any time.\n
# &b----------------------------------------------------"
#  - "&b ----------------------------------------------------\n
#a&nServer Hierarchy&r\n
#\n
#&ePresident: President_God\n
#&bVice President: mythguy1226\n
#&fJanitor: xSp4rkz\n
#&b----------------------------------------------------"
#  - "&b ----------------------------------------------------\n
#&a&lThe server requires rule a new rule master.\n
#&bIf you feel you would make a worthy rule master, please\n
#visit &6/warp plots &band build a set of rules that the\n
#server can abide by. On &aFeb 24th at 1pm CST &ba \n
#vote will begin\n on who made the best rules.\n
#Winner will be awarded offical rule master and\n
#be in charge of the server police force.\n
#You can read submissions of rules by using\n
#the command &6/warp rules<num> &b. For example,\n
#&6/warp rules3
#&b----------------------------------------------------"
#  - "&b ----------------------------------------------------\n
#&a&lTIME TO START VOTING ON &c&lBEST SERVER RULES\n
#&a&lTHE WINNER WILL BE THE NEW &c&lPOLICE CHIEF &a&lAND\n
#A NEW &c&lRULE MASTER&a&l!!!\n
#&c&lhttp://www.strawpoll.me/12410065\n
#&b----------------------------------------------------"
  - "&b ----------------------------------------------------\n
&f&lWant To Become Part Of Staff!?\n
&bTo Become Police Just Do &f&l/policequiz\n 
&bThen ask &f&lMrFlameYT &bTo Check It\n
&cTo Become Helper Just Do &f&l/helperquiz\n
&cThen ask &f&lSled_Gang &cTo Check It\n
&6To Become Builder Just Ask &f&lBlueRaven_\n
&6You Must Create A House Of Any Theme In &f&lPlots\n
&3To Become Coder Just Do &f&l/coderquiz\n
&3Then ask &f&lRqndomMyth &3To Check It\n
&9To Become Judge Just Do &f&l/judgequiz\n
&9Then ask &f&lRqndomPqrson &9To Check It\n
&b----------------------------------------------------"
  - "&b ----------------------------------------------------\n
&f&lBuilding Contest Information\n
&aTakes Place Every &f&lTuesday/Thursday/Saturday\n
&A6:00 &f&lCT&7&l/&a7:00 &f&lET&7&l/&a5:00 &f&lMT&7&l/&a4:00 &fPT - All Are In PM\n
&aWinner recieves the tag &3&lBuilding&f&lGod\n
&b----------------------------------------------------"
