Broadcast-Inverval: 5m
Auto-Broadcast: true
Random-Order: false
Ignore-Delay: 1h
Prefixes:
  Console: '&5[CONSOLE]&f '
  Default: ''
  '@W': '&4[WARNING]&f '
  '@T': '&5[TIP]&f '
Messages:
  - "&b ----------------------------------------------------\n
&7This server supports &aall canon &7(&4&lnot &4fanfic&7) &7characters&7\n
It is &lFEATS ONLY&7, meaning none of that wiki bullshit.\n
Only shit that's &lACTUALLY&7 been shown in a comic, game,\n
TV, Movie, or other fuckin' authorized merch.\n
&lONLY PICS OR VIDS COUNT AS PROOF, YA CUNTS!\n
&b----------------------------------------------------"
  - "&b ----------------------------------------------------\n
&7Handy fuckin' commands: &a/recipe&7, &a/co i&7, &a/home <plr>:&7,\n
&a/powers&7, &a/mortal&7, &a/disguiseviewself&7, &a/who&7,\n
&a/listheroes <pagenum>&7, &a/id <classname>&7\n
&b----------------------------------------------------"
  - "&b ----------------------------------------------------\n
&7New slave position available! &4Redstone Master&7\n
&6You will be forced fuck with &4bullshit redstone &6for\n
&4bullshit wages &6and given &4impossible tasks &6for which you\n
can't even edit the fuckin' commandblocks yourself\n
cuz fucking Mojang or some shit didn't make a way\n
to allow that unless you're the fucking server owner.\n
Mojang 1, you ZERO.\n
&4&lPOSITION STILL AVAILABLE.\n
&4&lPLEASE TALK TO Angel__Boy\n
&b----------------------------------------------------"
  - "&b ----------------------------------------------------\n
&7We now beg for irl money: &ahttps://goo.gl/BmxAqv&7\n
&b----------------------------------------------------"
  - "&b ----------------------------------------------------\n
&dIs the server fucked up?\n
&dAre we missing the most badass character of all time?\n
&4&lThen fucking click here\n
&ahttps://github.com/malonnnn/ServerConfig/issues\n
&b----------------------------------------------------"
  - "&b ----------------------------------------------------\n
&6Available Slave Positions\n
&e&lD&a&lN&4&lA &f&lEngineers&7 (makes heroes)\n
#&e&lD&a&lN&4&lA &a&lC&b&lo&c&ls&d&lm&e&le&f&lt&5&li&6&lc&2&ls&7 (makes skins)\n
&a&lVR &b&lConstructor&7 (builds shit)\n
&4Redstone Master&7 (fucks up redstone/commandblock bullshit)\n
&b----------------------------------------------------"
  - "&b ----------------------------------------------------\n
&a/warp rollercoaster&6 - this place sucks if you hate rollercoasters\n
&a/warp infiniteparkour&6 - the shortest parkour ever\n
&b----------------------------------------------------"
#  - "&b ----------------------------------------------------\n
#&a&lThe server requires rule a new rule master.\n
#&bIf you feel you would make a worthy rule master, please\n
#visit &6/warp plots &band build a set of rules that the\n
#server can abide by. On &aFeb 24th at 1pm CST &ba \n
#vote will begin\n on who made the best rules.\n
#Winner will be awarded offical rule master and\n
#be in charge of the server police force.\n
#You can read submissions of rules by using\n
#the command &6/warp rules<num> &b. For example,\n
#&6/warp rules3
#&b----------------------------------------------------"
#  - "&b ----------------------------------------------------\n
#&a&lTIME TO START VOTING ON &c&lBEST SERVER RULES\n
#&a&lTHE WINNER WILL BE THE NEW &c&lPOLICE CHIEF &a&lAND\n
#A NEW &c&lRULE MASTER&a&l!!!\n
#&c&lhttp://www.strawpoll.me/12410065\n
#&b----------------------------------------------------"
