Broadcast-Inverval: 5m
Auto-Broadcast: true
Random-Order: false
Ignore-Delay: 1h
Prefixes:
  Console: '&5[CONSOLE]&f '
  Default: ''
  '@W': '&4[WARNING]&f '
  '@T': '&5[TIP]&f '
Messages:
    - "&9TeamSpeak Server (that no one uses): &6mynecraft.servegame.com"
    - "&7You can be anyone you want on this server. A &9god&7, a &9superhero&7, a &9human&7, doesn't matter."
    - "&7Commands you should know: &9/recipe&7, &9/co i&7, &9/bal&7, &9/sell&7, and more! Visit &9/warp commandshall&7 !"
    - "&9The Rules&7: Do not be a jerk and no cheating! That is all."
    - "&7Need to contact the owner? Send an email to &6malonnnnn@gmail.com"
    - "&7Want to be a &9God&7? How about a &9superhero&7? How about &9anyone at all&7? Because this server is &9Awesome&7!"
    - "&7We now accept donations: &6https://goo.gl/BmxAqv"
    - "&7Want to join our &9staff &7team? &7Ask &9Tek &7for some &9work&7!"