Broadcast-Inverval: 5m
Auto-Broadcast: true
Random-Order: false
Ignore-Delay: 1h
Prefixes:
  Console: '&5[CONSOLE]&f '
  Default: ''
  '@W': '&4[WARNING]&f '
  '@T': '&5[TIP]&f '
Messages:
  - "&7 ----------------------------------------------------\n
This server supports all canon (&lnot &7fanfic) characters&7\n
----------------------------------------------------"
  - "&7 ----------------------------------------------------\n
Commands you should know: &a/recipe&7, &a/co i&7, &a/home <plr>:&7, &a/powers&7\n
----------------------------------------------------"
  - "&7 ----------------------------------------------------\n
Need to contact the owner? Send an email to &amalonnnnn@gmail.com&7\n
----------------------------------------------------"
  - "&7 ----------------------------------------------------\n
We now accept donations: &ahttps://goo.gl/BmxAqv&7\n
----------------------------------------------------"
  - "&7 ----------------------------------------------------\n
You can now go to &a/warp rules &7to see the new server rules!&7\n
----------------------------------------------------"
  - "&7 ----------------------------------------------------\n
Want free &lOP &7heroes? Then apply to be staff! &e&lD&a&lN&4&lA &f&lEngineers&7, &e&lD&a&lN&4&lA &a&lC&b&lo&c&ls&d&lm&e&le&f&lt&5&li&6&lc&2&ls&7, and &a&lVR &b&lConstructor&7! Drop off your application at &a/warp staffapps&7\n
----------------------------------------------------"
- "&7 ----------------------------------------------------\n
Tek go to Issues and read my two latest "Hey HEY!" and the other making sure you read.
----------------------------------------------------"

