Trail_Remove_Message: "&7Successfully changed trail to default."
Trail_Change_Message: "&7Successfully changed trail to #TRAIL#."
Trail_No_Gun_In_Hand_Message: "&7You have to be holding a gun to choose trail."
No_Trails_For_Gun_Message: "&7This gun does not have any trails."
Remove_Trail_Item:
    Item_Type: "291"
    Item_Name: "&c<-> &7Default &c<->"
    Item_Lore:
    - "&7Click me to change trail to default."
    Item_Durability: 66
Trail_Fill_Empty_Slots_Item:
    Item_Type: "160:7"
    Item_Name: "&c<&7-&c>"