GriefPrevention:
  Groups:
    Names: []
  DataStore: file
  DebugLevel: None
  Claims:
    MaxAccruedBlocks: 500000
    AutoSubClaimsSwitch: false
    DeleteWithUnrecognizedOwner: false
    InitialBlocks: 100
  Mods:
    Containers:
      IncludeRE: \schest\s|\schests\s|\sfurnace\s|\sgrinder\s|\sextruder\s|\smachine\s|\sengine\s|\sturtle\s|\saccumulator\s|\sprecipitator\s|\sAssembler\s|\sinfuser\s|\smachine\s|\sreceptacle\s|\s.*chest\s|\sTank\s|\sCrucible\s|smelter\s|\sworkbench\s|\stable\s|//sAutoCrafter//s|//sCharger//s|//sIceGen//s|//sSawmill//s|//sTransposer//s|//sWaterGen//s//s.*Shelf//s|//s.*Case//s|//s.*Rack//s|//s.*Label//s|//s.*Desk//s|//s.*Stand//s
      ExcludeRE: ''
    Access:
      IncludeRE: \sbutton\s|\sswitch\s|\sDoor\s|\sTrapdoor\s
      ExcludeRE: ''
    Trash:
      IncludeRE: \sOre\z|\sdirt\s
      ExcludeRE: ''
    PerformConfigSearch: false
  Economy:
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  EnableMoveWatcher: false
  GlobalClaimsEnabled: true
  GlobalPVPEnabled: true
  GlobalSiegeEnabled: true
  GlobalSpamEnabled: true
  AllowAutomaticMigration: true
  DisabledCommands: []
  Siege:
    CooldownTime: 3600000
  WorldConfig:
    SingleWorld: <None>
    TemplateFile: plugins/GriefPrevention/WorldConfigs/_template.cfg
