# DynamicSlot config
# 
# Use to fix slot at specified amount 
# put 1 into this if you want like ItsJerryAndHarry server
# Example: fixedslot: 1 , server will always have 1 slot (but player always can join)
# -1 = disable
fixedslot: -1
min: -1
max: -1
slotleft: 1
playerlimit: -3
kickfullmsg: -&c&lSORRY , SERVER IS FULL!%newline%PLEASE TRY AGAIN LATER.
mcstats: false
