#To change the message when you activate a particle you must use " %particle " to get the particle name!
ParticleMessage: '&eNow using the &b%particle &eparticle'

#Set this to true or false if you want to have the menu tool on join.
Items:
 OnJoin: false

#Change the lore of the item which opens the particle GUI.
ParticleMenuLore:
- '&7Particle Pack Menu Tool'
- '&7Right click to open'

#Change the slot of the item on join. 0-8
ParticleMenuSlot: 0

#Change the material of the item on join.
material: NETHER_STAR

#Change the particle menu tool name.
ParticleMenuName: '&aParticlePack'

#Change the GUI name for the particle menu.
ParticleMenuGUIName: '&bParticle Menu'

#Change the individual lore's of each item in the GUI, all of these lore's can use the color codes using "&".
FlameLore: '&7Left click to activate'

FireworkLore: '&7Left click to activate'

ColorLore: '&7Left click to activate'

EnchantLore: '&7Left click to activate'

EnderLore: '&7Left click to activate'

ExplosionLore: '&7Left click to activate'

LavaLore: '&7Left click to activate'

LoveLore: '&7Left click to activate'

MagicLore: '&7Left click to activate'

MusicLore: '&7Left click to activate'

PortalLore: '&7Left click to activate'

SlimeLore: '&7Left click to activate'

CritLore: '&7Left click to activate'

SmokeLore: '&7Left click to activate'

SnowballLore: '&7Left click to activate'

SparkLore: '&7Left click to activate'

SpellLore: '&7Left click to activate'

SplashLore: '&7Left click to activate'

VoidLore: '&7Left click to activate'

WaterdripLore: '&7Left click to activate'

CloudLore: '&7Left click to activate'

VillagerLore: '&7Left click to activate'

AngryLore: '&7Left click to activate'

WitchLore: '&7Left click to activate'

#This lore will change the lore of the deactivate particle item.
DeactivateLore: '&7Left click to deactivate a particle'

#This lore will change the lore of the next page item.
NextpageLore: '&7Left click to go to the next page'

#This lore will change the lore of the back to main menu item.
BacktomainLore: '&7Left click to go back to the main menu'

#Add blacklisted commands to disable certain commands the plugin offers.
BlacklistCMDs:
  -
