# Thanks for using my plugin =D #

Option:
  UpdateNotify: true
  BlockTime: 40
  Signs: false
  UseRaw: true
  RawMsg: '&c&oNo trails selected !'
  RawSelect: '&b&nClick here to open trail menu'
  NoTrailsPerm: '&eYou dont have permission to this trail'
  NoCmdPerm: '&eYou dont have permission'
  IfTrailsAllow: '&aALLOWED'
  IfTrailsDisallow: '&cYou Dont Have Permission'
  Line: '&6------------------'
  Selected: '&6You Selected &7'
  None: None
  Back: '&fBack to main menu'
  BackItemId: 381
  BackItemData: 0
  BackButton: true
  MsgRemove: '&cTrail was disabled'
  DisableWhenPlayerDontMoving: false
  TimeToDisable: 15
  KeepMenuOpen: false
  AutoRawDisable: true
  DefaultMenu: Main
  SaveTrails: false
  ModeChanger: false
  ModeChangerSlot: 4
  ModeChangerItemName: '&6&lChange mode'
  TList: My presents
  UnlockedBlocks: '&e!Count!/8'
  WingsTrail: true
  ChrismasItem: '&fMy Presents'
  UnlockedParticle: '&e!Count!/25'
  UnlockedRains: '&e!Count!/5'
  HideWingsInMoving: false
  InvisHide: false
  EventItem: '&fMy trails'
  BlockChestOpening: false
  Event: false
  EventMenuName: Chest opening...
  WingsMenu: Types
  WingsAnimation: false
  LimitPlayers: 10
  LimitMessage: '&cYou''re unable to select trail'
  LimitTrails: false
  RainFix: false
  RainMinimalTimeAlive: false
  PreventRainFromStuck: false
MultipleTrails:
  Enable: false
  AddedMsg: '&aAdded &7'
  Limit: 5
  VipLimit: 10
  AllR: '&cAll trails removed'
  LMsg: '&cYou have max trails limit'
  UMsg: '&cThis trail already used'
  BMsg: '&cYou cant use more than one block trail'
  RMsg: '&cYou cant use more than one rain trail'
Extra:
  ParticleItem: '&6&lParticle Trails'
  BlockItem: '&2&lBlock Trails'
  RainItem: '&3&lRain Trails'
  BetaItem: '&7&lBeta Trails'
  RemItem: '&c&lRemove Trails'
  ChooseTypeMenu: Choose Type
  ParticleMenu: Trails
  BlockMenu: Block Trails
  RainMenu: Rain Trails
  White: '&fWhite'
  Red: '&cRed'
  Yellow: '&eYellow'
  Green: '&aGreen'
  Blue: '&9Blue'
  Purple: '&dPurple'
  Black: '&7Black'
  RTBpage1: Rain Trails Builder 1/2
  RTBpage2: Rain Trails Builder 2/2
  BfW: '&eButterfly'
  Wings0: Select wings type
  AngelW: '&fAngel'
DonationButton:
  Enable: false
  Name: '&a&l!player!'
  Lore:
  - '&fHello'
  ID: 1
  Data: 0
  Message: Click here to donate
  Link: http://
RainPos:
  X: 0
  Y: 4
  Z: 0
  ItemY: 3
  ItemX: 0
  ItemZ: 0
Heart:
  Display: true
  Name: Heart Trail
  Item: '&cHeart'
  S: 9
  Y: 0.5
Angry:
  Display: true
  Name: Angry Trail
  Item: '&6Angry'
  S: 10
  Y: 2
Magic:
  Display: true
  Name: Magic Trail
  Item: '&3Magic'
  Speed: 0
  S: 11
  Y: 1
Fun:
  Display: true
  Name: Color Trail
  Item: '&eColors'
  S: 12
  Y: 0.5
Cloud:
  Display: true
  Name: Cloud Trail
  Item: '&fCloud'
  Speed: 0.0
  S: 13
  Y: 1
Witch:
  Display: true
  Name: Witch Trail
  Item: '&bWitch Magic'
  Speed: 0.3
  S: 14
  Y: 0.5
Ender:
  Display: true
  Name: Ender Trail
  Item: '&5Ender'
  Speed: 0.5
  S: 15
  Y: 0.5
Green:
  Display: true
  Name: Green Trail
  Item: '&aGreen'
  S: 16
  Y: 0.5
Spark:
  Display: true
  Name: Spark Trail
  Item: '&fSpark'
  Speed: 0.4
  S: 17
  Y: 0.5
Flame:
  Display: true
  Name: Flame Trail
  Item: '&6Flame'
  Speed: 0
  S: 18
  Y: 0.5
WhiteMagic:
  Display: true
  Name: White Magic Trail
  Item: '&fWite Magic'
  Speed: 0.3
  S: 19
  Y: 0.5
Note:
  Display: true
  Name: Music Trail
  Item: '&dMusic'
  S: 20
  Y: 0
Snow:
  Display: true
  Name: Snow Trail
  Item: '&fSnow'
  Speed: 0.2
  S: 21
  Y: 0.5
Water:
  Display: true
  Name: Water Trail
  Item: '&bWater'
  S: 22
  Y: 0.5
Lava:
  Display: true
  Name: Lava Trail
  Item: '&6Lava'
  S: 23
  Y: 0.5
Crit:
  Display: true
  Name: Crit Trail
  Item: '&6Crit'
  Speed: 0.2
  S: 24
  Y: 0.5
Smoke:
  Display: true
  Name: Smoke Trail
  Item: '&7Smoke'
  Speed: 0.2
  S: 25
  Y: 0.5
Spell:
  Display: true
  Name: Spell Trail
  Item: '&5Spell'
  S: 26
  Y: 0.5
Enchant:
  Display: true
  Name: Enchant Trail
  Item: '&fEnchant'
  Speed: 0
  S: 27
  Y: 0.5
Splash:
  Display: true
  Name: Splash Trail
  Item: '&9Splash'
  S: 28
  Y: 0.5
Slime:
  Display: true
  Name: Slime Trail
  Item: '&aSlime'
  S: 29
  Y: 0.5
Snowball:
  Display: true
  Name: Snowball Trail
  Item: '&fSnowballs'
  S: 30
  Y: 0.5
Spell2:
  Name: Spell2 Trail
  Y: 0.5
Red:
  Display: true
  Name: Red Trail
  Item: '&4Red'
  S: 31
  Y: 0.5
Void:
  Display: true
  Name: Void Trail
  Item: '&7Void'
  S: 31
  Y: 0.5
Pop:
  Display: true
  Name: Pop Trail
  Item: '&ePop'
  S: 32
  Y: 0.5
Blocks:
  Name:
    Rainbow: Rainbow Glass
    Flower: Flower Blocks
    Carpet: Carpet Blocks
    Redstone: Redstone Blocks
    Sea: Sea Blocks
    Wheat: Wheat Blocks
    Ore: Ore Blocks
    Clay: Clay Blocks
  Items:
    Rainbow: '&fRainbow Blocks'
    Flower: '&cFlower Blocks'
    Carpet: '&eCarpet Blocks'
    Redstone: '&aRedstone Blocks'
    Sea: '&9Sea Blocks'
    Wheat: '&5Wheat Blocks'
    Ore: '&6Ore Blocks'
    Clay: '&3Clay Blocks'
  Slot:
    Rainbow: 11
    Flower: 12
    Carpet: 13
    Redstone: 14
    Sea: 15
    Wheat: 22
    Ore: 21
    Clay: 23
Rains:
  Name:
    Tear: Tear Rain
    Blood: Blood Rain
    Dia: Dia Rain
    Wart: Wart Rain
    Gold: Gold Rain
    Builder: Custom Rain
  Items:
    Tear: '&6Tear Rain'
    Blood: '&4Blood Rain'
    Dia: '&bDia Rain'
    Wart: '&5Wart Rain'
    Gold: '&6Gold Rain'
    Builder: '&aRain Builder'
  Slot:
    Tear: 11
    Blood: 12
    Dia: 13
    Wart: 14
    Gold: 15
    Builder: 31
Signs:
  Line4: ' '
  Line1: '&lClick to open'
  Line2: '&ltrails menu'
  Line3: '&8&n!T!'
MySQL:
  database: db
  password: password
  port: 3306
  host: localhost
  Enable: false
  user: user
