Visual_Reload_Remove_Message: "&7Successfully changed visual reload to default."
Visual_Reload_Change_Message: "&7Successfully changed visual reload to #VISUALRELOAD#."
Visual_Reload_No_Gun_In_Hand_Message: "&7You have to be holding a gun to choose visual reload."
No_Visual_Reload_For_Gun_Message: "&7This gun does not have any visual reloads."
Remove_Visual_Reload_Item:
    Item_Type: "291"
    Item_Name: "&c<-> &7Default &c<->"
    Item_Lore:
    - "&7Click me to change visual reload to default."
    Item_Durability: 66
Visual_Reload_Fill_Empty_Slots_Item:
    Item_Type: "160:7"
    Item_Name: "&c<&7-&c>"