# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    '1_9': -1
    1_9_nether: -1
    1_9_the_end: -1
    skeeter_nether: -1
    rollercoaster: -1
    elytralobby: -1
    skywarslobby: -1
    parkourmedium: -1
    formuladrift: -1
    speedforce: -1
    fortressofsolitude: -1
    flyingbattlelobby: -1
    elytraeasy: -1
    hallofworlds: -1
    megaparkour: -1
    gotham: -1
    hurdles: -1
    godlyparkour: -1
    chess: -1
    marathon: -1
    hallofjustice: -1
    metropolis: -1
    anarchy: -1
    longparkour: -1
    spleef: -1
    creative: -1
    towerparkour: -1
    parkourhub: -1
    boatrace: -1
    elytrahard: -1
    lavahop: -1
    skeeter_the_end: -1
    checkers: -1
    obstaclecourse: -1
    deathdrop: -1
    flappybirdparkour: -1
    wooftywoo: -1
    parkoureasy: -1
    destructiblecity: -1
    skywars: -1
    hilariousrace: -1
    titanstower: -1
    flat: -1
    infiniteparkour: -1
    turbotowers: -1
    straightlineparkour: -1
    colosseum: -1
    greenfield: -1
    waynemanor: -1
    spleeflobby: -1
    wallenpole: -1
    parkourhard: -1
    colosseumlobby: -1
    skeeter: -1
    elytramedium: -1
    shortparkour: -1
    plots: -1
    torture: -1
    spawn: -1
    flyingbattlearena: -1
    infinitycity: -1
  Claims:
    Mode:
      parkourhub: Disabled
      parkoureasy: Disabled
      checkers: Disabled
      spleef: Disabled
      destructiblecity: Disabled
      skywarslobby: Disabled
      hallofworlds: Disabled
      flyingbattlearena: Disabled
      colosseumlobby: Disabled
      skeeter_the_end: Survival
      deathdrop: Disabled
      elytralobby: Disabled
      plots: Survival
      wooftywoo: Disabled
      creative: Creative
      megaparkour: Disabled
      formuladrift: Disabled
      fortressofsolitude: Disabled
      longparkour: Disabled
      wallenpole: Disabled
      godlyparkour: Disabled
      straightlineparkour: Disabled
      towerparkour: Disabled
      flappybirdparkour: Disabled
      flat: Creative
      spleeflobby: Disabled
      marathon: Disabled
      lavahop: Disabled
      greenfield: Disabled
      infinitycity: Disabled
      chess: Disabled
      waynemanor: Disabled
      gotham: Disabled
      elytraeasy: Disabled
      elytrahard: Disabled
      speedforce: Survival
      hallofjustice: Disabled
      spawn: Disabled
      obstaclecourse: Disabled
      1_9_the_end: Survival
      parkourmedium: Disabled
      1_9_nether: Survival
      hurdles: Disabled
      shortparkour: Disabled
      parkourhard: Disabled
      anarchy: Disabled
      turbotowers: Disabled
      elytramedium: Disabled
      torture: Disabled
      flyingbattlelobby: Disabled
      skeeter: Survival
      boatrace: Disabled
      rollercoaster: Survival
      metropolis: Disabled
      hilariousrace: Disabled
      '1_9': Survival
      colosseum: Disabled
      skywars: Disabled
      titanstower: Survival
      skeeter_nether: Survival
      infiniteparkour: Disabled
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    ProtectHorses: true
    InitialBlocks: 100
    Claim Blocks Accrued Per Hour:
      Default: 500
    Max Accrued Claim Blocks:
      Default: 500000
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLD_SPADE
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 14
      AllClaims:
        DaysInactive: 60
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    PortalGenerationRequiresPermission: false
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
  Spam:
    Enabled: true
    LoginCooldownSeconds: 60
    ChatSlashCommands: /me;/tell;/global;/local;/w;/msg;/r;/t
    WhisperSlashCommands: /tell;/pm;/r;/w;/whisper;/t;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: false
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 0
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      '1_9': true
      1_9_nether: true
      1_9_the_end: true
      skeeter_nether: true
      rollercoaster: true
      elytralobby: true
      skywarslobby: true
      parkourmedium: true
      formuladrift: true
      speedforce: true
      fortressofsolitude: true
      flyingbattlelobby: true
      elytraeasy: true
      hallofworlds: true
      megaparkour: false
      gotham: true
      hurdles: true
      godlyparkour: true
      chess: true
      marathon: true
      hallofjustice: true
      metropolis: true
      anarchy: true
      longparkour: true
      spleef: true
      creative: false
      towerparkour: true
      parkourhub: true
      boatrace: true
      elytrahard: true
      lavahop: true
      skeeter_the_end: true
      checkers: true
      obstaclecourse: true
      deathdrop: true
      flappybirdparkour: true
      wooftywoo: true
      parkoureasy: true
      destructiblecity: true
      skywars: true
      hilariousrace: true
      titanstower: true
      flat: false
      infiniteparkour: true
      turbotowers: true
      straightlineparkour: true
      colosseum: true
      greenfield: true
      waynemanor: true
      spleeflobby: true
      wallenpole: true
      parkourhard: true
      colosseumlobby: true
      skeeter: true
      elytramedium: true
      shortparkour: true
      plots: false
      torture: true
      spawn: false
      flyingbattlearena: true
      infinitycity: true
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa;/warp;/tpa;/tp;
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers: true
    AllowFlintAndSteelNearOtherPlayers: true
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: false
  LimitSkyTrees: true
  LimitTreeGrowth: false
  LimitPistonsToLandClaims: false
  FireSpreads: true
  FireDestroys: true
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 99
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS
    - LONG_GRASS
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - THIN_GLASS
    - WOOD
    - WOOL
    - SNOW
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Mods:
    BlockIdsRequiringAccessTrust: []
    BlockIdsRequiringContainerTrust:
    - 99999:*:Example - ID 99999, all data values.
    BlockIdsExplodable: []
    PlayersIgnoringAllClaims: []
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false
