# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    survival: -1
    survival_nether: -1
    survival_the_end: -1
    skeeter_nether: -1
    rollercoaster: -1
    newcity: -1
    elytralobby: -1
    skywarslobby: -1
    parkourmedium: -1
    formuladrift: -1
    speedforce: -1
    fortressofsolitude: -1
    flyingbattlelobby: -1
    elytraeasy: -1
    megaparkour: -1
    gotham: -1
    hurdles: -1
    godlyparkour: -1
    chess: -1
    marathon: -1
    hallofjustice: -1
    metropolis: -1
    anarchy: -1
    longparkour: -1
    spleef: -1
    towerparkour: -1
    parkourhub: -1
    boatrace: -1
    elytrahard: -1
    lavahop: -1
    skeeter_the_end: -1
    checkers: -1
    obstaclecourse: -1
    deathdrop: -1
    flappybirdparkour: -1
    wooftywoo: -1
    parkoureasy: -1
    destructiblecity: -1
    skywars: -1
    hilariousrace: -1
    lasertag: -1
    titanstower: -1
    infiniteparkour: -1
    turbotowers: -1
    straightlineparkour: -1
    colosseum: -1
    greenfield: -1
    waynemanor: -1
    spleeflobby: -1
    wallenpole: -1
    parkourhard: -1
    colosseumlobby: -1
    garbageworld: -1
    skeeter: -1
    anarchy_nether: -1
    elytramedium: -1
    shortparkour: -1
    plots: -1
    torture: -1
    spawn: -1
    flyingbattlearena: -1
    infinitycity: -1
  Claims:
    Mode:
      parkourhub: Disabled
      parkoureasy: Disabled
      checkers: Disabled
      spleef: Disabled
      destructiblecity: Disabled
      skywarslobby: Disabled
      survival_the_end: Survival
      flyingbattlearena: Disabled
      colosseumlobby: Disabled
      skeeter_the_end: Survival
      deathdrop: Disabled
      elytralobby: Disabled
      plots: Disabled
      wooftywoo: Disabled
      megaparkour: Disabled
      formuladrift: Disabled
      lasertag: Survival
      fortressofsolitude: Disabled
      longparkour: Disabled
      wallenpole: Disabled
      godlyparkour: Disabled
      straightlineparkour: Disabled
      towerparkour: Disabled
      flappybirdparkour: Disabled
      spleeflobby: Disabled
      garbageworld: Survival
      marathon: Disabled
      lavahop: Disabled
      greenfield: Disabled
      survival: Survival
      infinitycity: Disabled
      chess: Disabled
      waynemanor: Disabled
      gotham: Disabled
      elytraeasy: Disabled
      elytrahard: Disabled
      newcity: Survival
      speedforce: Disabled
      survival_nether: Survival
      hallofjustice: Disabled
      spawn: Disabled
      obstaclecourse: Disabled
      parkourmedium: Disabled
      anarchy_nether: Disabled
      hurdles: Disabled
      shortparkour: Disabled
      parkourhard: Disabled
      anarchy: Disabled
      turbotowers: Disabled
      elytramedium: Disabled
      torture: Disabled
      flyingbattlelobby: Disabled
      skeeter: Survival
      boatrace: Disabled
      rollercoaster: Disabled
      metropolis: Disabled
      hilariousrace: Disabled
      colosseum: Disabled
      skywars: Disabled
      titanstower: Disabled
      skeeter_nether: Disabled
      infiniteparkour: Disabled
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    ProtectHorses: true
    InitialBlocks: 100
    Claim Blocks Accrued Per Hour:
      Default: 500
    Max Accrued Claim Blocks:
      Default: 500000
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLD_SPADE
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 14
      AllClaims:
        DaysInactive: 60
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    PortalGenerationRequiresPermission: false
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
  Spam:
    Enabled: true
    LoginCooldownSeconds: 60
    ChatSlashCommands: /me;/tell;/global;/local;/w;/msg;/r;/t
    WhisperSlashCommands: /tell;/pm;/r;/w;/whisper;/t;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: false
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 0
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      survival: true
      survival_nether: true
      survival_the_end: true
      skeeter_nether: false
      rollercoaster: false
      newcity: true
      elytralobby: false
      skywarslobby: false
      parkourmedium: false
      formuladrift: false
      speedforce: false
      fortressofsolitude: false
      flyingbattlelobby: false
      elytraeasy: false
      megaparkour: false
      gotham: false
      hurdles: false
      godlyparkour: false
      chess: false
      marathon: false
      hallofjustice: false
      metropolis: false
      anarchy: false
      longparkour: false
      spleef: false
      towerparkour: false
      parkourhub: false
      boatrace: false
      elytrahard: false
      lavahop: false
      skeeter_the_end: false
      checkers: false
      obstaclecourse: false
      deathdrop: false
      flappybirdparkour: false
      wooftywoo: false
      parkoureasy: false
      destructiblecity: false
      skywars: false
      hilariousrace: false
      lasertag: true
      titanstower: false
      infiniteparkour: false
      turbotowers: false
      straightlineparkour: false
      colosseum: false
      greenfield: false
      waynemanor: false
      spleeflobby: false
      wallenpole: false
      parkourhard: false
      colosseumlobby: false
      garbageworld: true
      skeeter: false
      anarchy_nether: true
      elytramedium: false
      shortparkour: false
      plots: false
      torture: false
      spawn: false
      flyingbattlearena: false
      infinitycity: false
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa;/warp;/tpa;/tp;
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers: true
    AllowFlintAndSteelNearOtherPlayers: true
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: false
  LimitSkyTrees: true
  LimitTreeGrowth: false
  LimitPistonsToLandClaims: false
  FireSpreads: true
  FireDestroys: true
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 99
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS
    - LONG_GRASS
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - THIN_GLASS
    - WOOD
    - WOOL
    - SNOW
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Mods:
    BlockIdsRequiringAccessTrust: []
    BlockIdsRequiringContainerTrust:
    - 99999:*:Example - ID 99999, all data values.
    BlockIdsExplodable: []
    PlayersIgnoringAllClaims: []
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false
