# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    survival112: -1
    survival112_nether: -1
    survival112_the_end: -1
    moblottery: -1
    vigilance_ruined_plots: -1
    elytralobby: -1
    skywarslobby: -1
    parkourmedium: -1
    formuladrift: -1
    speedforce: -1
    fortressofsolitude: -1
    lexstarklabs: -1
    runner: -1
    turfwars: -1
    hurdles: -1
    atlantis: -1
    crossfire: -1
    metropolis: -1
    classroom: -1
    longparkour: -1
    mazerunner: -1
    spleef: -1
    shootingrange: -1
    towerparkour: -1
    boatrace: -1
    pvpworldsforest: -1
    hurdles2: -1
    lavahop: -1
    freezetag: -1
    minecraftparkourmode: -1
    broville: -1
    elytrapole: -1
    pvpworldsundergroundarmory: -1
    theworldroom: -1
    obstaclecourse: -1
    parkoureasy: -1
    vampirez: -1
    hilariousrace: -1
    pvpparkour: -1
    titanstower: -1
    skywarsbackup: -1
    straightlineparkour: -1
    waynemanor: -1
    parkourhard: -1
    colosseumlobby: -1
    splegg: -1
    torture: -1
    deathrun: -1
    deathmachine: -1
    flyingbattlearena: -1
    sprintparkour: -1
    rollercoaster: -1
    parksideprisonescape: -1
    fightclub: -1
    pvpworldsruins: -1
    flyingbattlelobby: -1
    elytraeasy: -1
    gotham: -1
    megaparkour: -1
    godlyparkour: -1
    starlabs: -1
    chess: -1
    hallofjustice: -1
    techcombatknockbackgame: -1
    anarchy: -1
    leafdecay: -1
    infectiontag: -1
    elytrahard: -1
    verticalparkour: -1
    extremesumo: -1
    checkers: -1
    quickparkour: -1
    flappybirdparkour: -1
    deathdrop: -1
    heroicparkour: -1
    lasertag: -1
    pvpparkourlobby: -1
    infiniteparkour: -1
    turbotowers: -1
    colosseum: -1
    soccer: -1
    greenfield: -1
    spleeflobby: -1
    wallenpole: -1
    kingoftheladder: -1
    anarchy_nether: -1
    hogwarts: -1
    elytramedium: -1
    elytrapvp: -1
    shortparkour: -1
    plots: -1
    overvoid: -1
    spawn: -1
    nyc: -1
    labyrinth: -1
    pvpworldslobby: -1
    infinitycity: -1
  Claims:
    Mode:
      deathrun: Disabled
      parkoureasy: Disabled
      plots: Survival
      flyingbattlearena: Disabled
      colosseumlobby: Disabled
      elytralobby: Disabled
      quickparkour: Disabled
      hogwarts: Disabled
      fightclub: Disabled
      deathmachine: Disabled
      pvpparkourlobby: Disabled
      pvpparkour: Disabled
      megaparkour: Disabled
      lasertag: Disabled
      wallenpole: Disabled
      godlyparkour: Disabled
      classroom: Survival
      sprintparkour: Disabled
      waynemanor: Disabled
      towerparkour: Disabled
      flappybirdparkour: Disabled
      survival112_the_end: Survival
      lexstarklabs: Disabled
      minecraftparkourmode: Disabled
      gotham: Disabled
      hallofjustice: Disabled
      spawn: Disabled
      starlabs: Disabled
      heroicparkour: Disabled
      overvoid: Disabled
      runner: Disabled
      atlantis: Disabled
      shortparkour: Disabled
      anarchy: Disabled
      turbotowers: Disabled
      elytramedium: Disabled
      flyingbattlelobby: Disabled
      metropolis: Disabled
      broville: Disabled
      theworldroom: Disabled
      titanstower: Disabled
      parksideprisonescape: Disabled
      splegg: Disabled
      infiniteparkour: Disabled
      checkers: Disabled
      spleef: Disabled
      skywarslobby: Disabled
      verticalparkour: Disabled
      deathdrop: Disabled
      leafdecay: Survival
      freezetag: Disabled
      pvpworldsundergroundarmory: Disabled
      formuladrift: Disabled
      fortressofsolitude: Disabled
      techcombatknockbackgame: Disabled
      longparkour: Disabled
      straightlineparkour: Disabled
      nyc: Disabled
      vampirez: Disabled
      crossfire: Disabled
      hurdles2: Disabled
      labyrinth: Disabled
      spleeflobby: Disabled
      turfwars: Disabled
      lavahop: Disabled
      greenfield: Disabled
      skywarsbackup: Survival
      infinitycity: Disabled
      chess: Disabled
      pvpworldsforest: Disabled
      kingoftheladder: Disabled
      vigilance_ruined_plots: Survival
      pvpworldslobby: Disabled
      elytrapole: Disabled
      elytraeasy: Disabled
      elytrahard: Disabled
      speedforce: Disabled
      survival112: Survival
      obstaclecourse: Disabled
      infectiontag: Disabled
      parkourmedium: Disabled
      moblottery: Disabled
      anarchy_nether: Disabled
      hurdles: Disabled
      parkourhard: Disabled
      survival112_nether: Survival
      pvpworldsruins: Disabled
      torture: Disabled
      extremesumo: Disabled
      boatrace: Disabled
      mazerunner: Disabled
      rollercoaster: Disabled
      soccer: Disabled
      shootingrange: Disabled
      hilariousrace: Disabled
      colosseum: Disabled
      elytrapvp: Disabled
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    ProtectHorses: true
    InitialBlocks: 100
    Claim Blocks Accrued Per Hour:
      Default: 100
    Max Accrued Claim Blocks:
      Default: 10000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLD_SPADE
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 14
      AllClaims:
        DaysInactive: 60
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    PortalGenerationRequiresPermission: false
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
  Spam:
    Enabled: true
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: false
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 0
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      survival112: true
      survival112_nether: true
      survival112_the_end: true
      moblottery: false
      vigilance_ruined_plots: true
      elytralobby: false
      skywarslobby: false
      parkourmedium: false
      formuladrift: false
      speedforce: true
      fortressofsolitude: true
      lexstarklabs: true
      runner: false
      turfwars: true
      hurdles: false
      atlantis: true
      crossfire: true
      metropolis: false
      classroom: true
      longparkour: false
      mazerunner: false
      spleef: false
      shootingrange: true
      towerparkour: false
      boatrace: false
      pvpworldsforest: true
      hurdles2: false
      lavahop: false
      freezetag: true
      minecraftparkourmode: false
      broville: true
      elytrapole: false
      pvpworldsundergroundarmory: true
      theworldroom: true
      obstaclecourse: false
      parkoureasy: false
      vampirez: false
      hilariousrace: false
      pvpparkour: false
      titanstower: true
      skywarsbackup: true
      straightlineparkour: false
      waynemanor: true
      parkourhard: false
      colosseumlobby: false
      splegg: true
      torture: false
      deathrun: false
      deathmachine: false
      flyingbattlearena: true
      sprintparkour: false
      rollercoaster: false
      parksideprisonescape: false
      fightclub: true
      pvpworldsruins: true
      flyingbattlelobby: false
      elytraeasy: false
      gotham: true
      megaparkour: false
      godlyparkour: false
      starlabs: true
      chess: false
      hallofjustice: false
      techcombatknockbackgame: true
      anarchy: false
      leafdecay: true
      infectiontag: true
      elytrahard: false
      verticalparkour: false
      extremesumo: true
      checkers: false
      quickparkour: false
      flappybirdparkour: false
      deathdrop: false
      heroicparkour: false
      lasertag: true
      pvpparkourlobby: false
      infiniteparkour: false
      turbotowers: false
      colosseum: true
      soccer: false
      greenfield: true
      spleeflobby: false
      wallenpole: false
      kingoftheladder: true
      anarchy_nether: true
      hogwarts: true
      elytramedium: false
      elytrapvp: true
      shortparkour: false
      plots: true
      overvoid: false
      spawn: false
      nyc: true
      labyrinth: false
      pvpworldslobby: false
      infinitycity: true
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers: true
    AllowFlintAndSteelNearOtherPlayers: true
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: false
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  LimitPistonsToLandClaims: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: false
  AdminsGetSignNotifications: false
  SmartBan: false
  Mute New Players Using Banned Words: false
  MaxPlayersPerIpAddress: 3
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS
    - LONG_GRASS
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - THIN_GLASS
    - WOOD
    - WOOL
    - SNOW
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Mods:
    BlockIdsRequiringAccessTrust: []
    BlockIdsRequiringContainerTrust:
    - 99999:*:Example - ID 99999, all data values.
    BlockIdsExplodable: []
    PlayersIgnoringAllClaims: []
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false
