# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    survival112: -1
    survival112_nether: -1
    survival112_the_end: -1
    moblottery: -1
    vigilance_ruined_plots: -1
    speedforce: -1
    fortressofsolitude: -1
    lexstarklabs: -1
    hurdles: -1
    atlantis: -1
    crossfire: -1
    metropolis: -1
    classroom: -1
    longparkour: -1
    spleef: -1
    boatrace: -1
    lavahop: -1
    soulstone: -1
    broville: -1
    obstaclecourse: -1
    parkoureasy: -1
    hilariousrace: -1
    titanstower: -1
    straightlineparkour: -1
    waynemanor: -1
    parkourhard: -1
    colosseumlobby: -1
    torture: -1
    deathrun: -1
    rollercoaster: -1
    fightclub: -1
    ooo: -1
    elytraeasy: -1
    megaparkour: -1
    gotham: -1
    starlabs: -1
    rapunzel: -1
    chess: -1
    hallofjustice: -1
    elytrarace: -1
    leafdecay: -1
    elytrahard: -1
    verticalparkour: -1
    checkers: -1
    deathdrop: -1
    flappybirdparkour: -1
    lasertag: -1
    infiniteparkour: -1
    colosseum: -1
    greenfield: -1
    spleeflobby: -1
    hogwarts: -1
    overvoid: -1
    nyc: -1
    infinitycity: -1
  Claims:
    Mode:
      deathrun: Disabled
      parkoureasy: Disabled
      checkers: Disabled
      spleef: Disabled
      verticalparkour: Disabled
      colosseumlobby: Disabled
      deathdrop: Disabled
      leafdecay: Disabled
      hogwarts: Disabled
      fightclub: Disabled
      megaparkour: Disabled
      lasertag: Disabled
      fortressofsolitude: Disabled
      longparkour: Disabled
      straightlineparkour: Disabled
      elytrarace: Disabled
      classroom: Disabled
      nyc: Disabled
      crossfire: Disabled
      waynemanor: Disabled
      flappybirdparkour: Disabled
      spleeflobby: Disabled
      survival112_the_end: Survival
      lavahop: Disabled
      lexstarklabs: Disabled
      greenfield: Disabled
      infinitycity: Disabled
      chess: Disabled
      vigilance_ruined_plots: Disabled
      rapunzel: Disabled
      soulstone: Disabled
      elytraeasy: Disabled
      gotham: Disabled
      elytrahard: Disabled
      speedforce: Disabled
      survival112: Survival
      hallofjustice: Disabled
      ooo: Disabled
      obstaclecourse: Disabled
      starlabs: Disabled
      moblottery: Disabled
      overvoid: Disabled
      atlantis: Disabled
      hurdles: Disabled
      parkourhard: Disabled
      survival112_nether: Survival
      torture: Disabled
      boatrace: Disabled
      metropolis: Disabled
      rollercoaster: Disabled
      broville: Disabled
      hilariousrace: Disabled
      colosseum: Disabled
      titanstower: Disabled
      infiniteparkour: Disabled
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    ProtectHorses: true
    InitialBlocks: 100
    Claim Blocks Accrued Per Hour:
      Default: 100
    Max Accrued Claim Blocks:
      Default: 10000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLD_SPADE
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 14
      AllClaims:
        DaysInactive: 60
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    PortalGenerationRequiresPermission: false
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: false
    ManualDeliveryDelaySeconds: 30
  Spam:
    Enabled: true
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: false
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 0
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      survival112: true
      survival112_nether: true
      survival112_the_end: true
      moblottery: true
      vigilance_ruined_plots: true
      speedforce: true
      fortressofsolitude: true
      lexstarklabs: true
      hurdles: true
      atlantis: true
      crossfire: true
      metropolis: true
      classroom: true
      longparkour: true
      spleef: true
      boatrace: true
      lavahop: true
      soulstone: true
      broville: true
      obstaclecourse: true
      parkoureasy: true
      hilariousrace: true
      titanstower: true
      straightlineparkour: true
      waynemanor: true
      parkourhard: true
      colosseumlobby: true
      torture: true
      deathrun: true
      rollercoaster: true
      fightclub: true
      ooo: true
      elytraeasy: true
      megaparkour: true
      gotham: true
      starlabs: true
      rapunzel: true
      chess: true
      hallofjustice: true
      elytrarace: true
      leafdecay: true
      elytrahard: true
      verticalparkour: true
      checkers: true
      deathdrop: true
      flappybirdparkour: true
      lasertag: true
      infiniteparkour: true
      colosseum: true
      greenfield: true
      spleeflobby: true
      hogwarts: true
      overvoid: true
      nyc: true
      infinitycity: true
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers: true
    AllowFlintAndSteelNearOtherPlayers: true
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: false
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  LimitPistonsToLandClaims: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: false
  AdminsGetSignNotifications: false
  SmartBan: false
  Mute New Players Using Banned Words: false
  MaxPlayersPerIpAddress: 3
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS
    - LONG_GRASS
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - THIN_GLASS
    - WOOD
    - WOOL
    - SNOW
    DoorsOpenDelayInSeconds: 300
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Mods:
    BlockIdsRequiringAccessTrust: []
    BlockIdsRequiringContainerTrust:
    - 99999:*:Example - ID 99999, all data values.
    BlockIdsExplodable: []
    PlayersIgnoringAllClaims: []
  Advanced:
    fixNegativeClaimblockAmounts: true
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false
