# 
# Whether or not resourcepack file hashes should be generated on startup:
debug: true
autogeneratehashes: true
messages:
  usepack: You now use the pack %pack%!
  packlisthead: 'Packs available to you:'
  nopacks: No packs found!
packs:
  broville:
    url: http://mynecraft.servegame.com/broville.zip
    hash: 96985bb0d3f89a1035706a067b8a7761b408f6d1
    format: 3
    restricted: false
    permission: worldresourcepacks.pack.broville
  greenfield:
    url: http://mynecraft.servegame.com/greenfield.zip
    hash: 1e4e28db225daabdbad18b27d31db32bdd436fa7
    format: 1
    restricted: false
    permission: worldresourcepacks.pack.greenfields
  gotham:
    url: http://mynecraft.servegame.com/gotham.zip
    hash: 1e4e28db225daabdbad18b27d31db32bdd436fa7
    format: 1
    restricted: false
    permission: worldresourcepacks.pack.gotham
  survival:
    url: http://mynecraft.servegame.com/pp.zip
    hash: 1e4e28db225daabdbad18b27d31db32bdd436fa7
    format: 3
    restricted: false
    permission: worldresourcepacks.pack.survival
empty: survival
server:
  pack: none
worlds:
  survival112:
    pack: survival
  gotham:
    pack: gotham
  greenfield:
    pack: greenfield
  broville:
    pack: broville
